/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author moral
 */
public class Pago extends javax.swing.JFrame {
    //variables globales 
    Connection con;
    int matriculaPasajero;
    boolean esTarjetaNueva = false;
    
    private boolean tieneTarjeta() {

    try {
        con = conexion.conectar();

        String sql =
        "SELECT * FROM tarjeta WHERE matricula_pasajero=?";

        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, matriculaPasajero);

        ResultSet rs = ps.executeQuery();

        return rs.next();

    } catch (SQLException e) {
        e.printStackTrace();
    }

    return false;
}
    
    private void cargarTarjeta() {

    try {
        con = conexion.conectar();

        String sql =
        "SELECT numero_tarjeta, titular, vencimiento " +
        "FROM tarjeta WHERE matricula_pasajero=?";

        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, matriculaPasajero);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            txtNumero.setText(rs.getString("numero_tarjeta"));
            txtTitular.setText(rs.getString("titular"));
            txtVencimiento.setText(rs.getString("vencimiento"));

        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pago.class.getName());

    /**
     * Creates new form Pago
     */
    public Pago() {
        initComponents();
    }
    public Pago(int matricula){

    this();

    this.matriculaPasajero = matricula;

    cargarCosto();

    // SI YA TIENE TARJETA → AUTORELLENA
    if (tieneTarjeta()) {

        rbTarjeta.setSelected(true);
        rbTarjetaActionPerformed(null);
        cargarTarjeta();

    } 
    else {

        rbEfectivo.setSelected(true);
        rbEfectivoActionPerformed(null);

        // ocultar campos tarjeta
        lblNumero.setVisible(false);
        txtNumero.setVisible(false);

        lblTitular.setVisible(false);
        txtTitular.setVisible(false);

        lblVencimiento.setVisible(false);
        txtVencimiento.setVisible(false);

        lblCVV.setVisible(false);
        txtCVV.setVisible(false);
    }
}
    
    private void cargarCosto(){

    try{

        con = conexion.conectar();

        String sql =

        "SELECT costo_estimado " +
        "FROM pago p " +
        "JOIN solicitud_viaje s " +
        "ON p.id_solicitud=s.id_solicitud " +
        "WHERE s.matricula_pasajero=? " +
        "ORDER BY p.id_pago DESC";

        PreparedStatement ps =
        con.prepareStatement(sql);

        ps.setInt(
        1,
        matriculaPasajero
        );

        ResultSet rs =
        ps.executeQuery();

        if(rs.next()){

            double costo =
            rs.getDouble(
            "costo_estimado"
            );

            lblCosto.setText(
            "Costo total: $" +
            String.format("%.2f", costo)
            );

        }

        rs.close();
        ps.close();
        con.close();

    }

    catch(SQLException e){

        e.printStackTrace();

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCVV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        rbEfectivo = new javax.swing.JRadioButton();
        btnUsarTarjeta = new javax.swing.JButton();
        rbTarjeta = new javax.swing.JRadioButton();
        btnNuevaTarjeta = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblTitular = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        lblVencimiento = new javax.swing.JLabel();
        txtVencimiento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 253, 244));

        lblCVV.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        lblCVV.setForeground(new java.awt.Color(22, 163, 74));
        lblCVV.setText("🔐 CVV: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(22, 163, 74));
        jLabel2.setText("💰 Método de pago: ");

        txtCVV.addActionListener(this::txtCVVActionPerformed);

        rbEfectivo.setBackground(new java.awt.Color(240, 253, 244));
        buttonGroup1.add(rbEfectivo);
        rbEfectivo.setForeground(new java.awt.Color(55, 65, 81));
        rbEfectivo.setSelected(true);
        rbEfectivo.setText("💵 Efectivo");
        rbEfectivo.addActionListener(this::rbEfectivoActionPerformed);

        btnUsarTarjeta.setForeground(new java.awt.Color(107, 114, 128));
        btnUsarTarjeta.setText("Usar tarjeta");
        btnUsarTarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 247, 208)));
        btnUsarTarjeta.setFocusPainted(false);
        btnUsarTarjeta.addActionListener(this::btnUsarTarjetaActionPerformed);

        rbTarjeta.setBackground(new java.awt.Color(240, 253, 244));
        buttonGroup1.add(rbTarjeta);
        rbTarjeta.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        rbTarjeta.setForeground(new java.awt.Color(55, 65, 81));
        rbTarjeta.setText("💳 Tarjeta ");
        rbTarjeta.addActionListener(this::rbTarjetaActionPerformed);

        btnNuevaTarjeta.setForeground(new java.awt.Color(107, 114, 128));
        btnNuevaTarjeta.setText("Nueva tarjeta");
        btnNuevaTarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 247, 208)));
        btnNuevaTarjeta.setFocusPainted(false);
        btnNuevaTarjeta.addActionListener(this::btnNuevaTarjetaActionPerformed);

        btnPagar.setBackground(new java.awt.Color(22, 163, 74));
        btnPagar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("✅ Confirmar pago");
        btnPagar.setBorderPainted(false);
        btnPagar.setFocusPainted(false);
        btnPagar.addActionListener(this::btnPagarActionPerformed);

        lblNumero.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(22, 163, 74));
        lblNumero.setText("🔢 Número:");

        txtNumero.addActionListener(this::txtNumeroActionPerformed);

        lblTitular.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        lblTitular.setForeground(new java.awt.Color(22, 163, 74));
        lblTitular.setText("👤 Titular: ");

        lblVencimiento.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        lblVencimiento.setForeground(new java.awt.Color(22, 163, 74));
        lblVencimiento.setText("📅 Vencimiento: ");

        jPanel2.setBackground(new java.awt.Color(22, 163, 74));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("💳 Pago del viaje");

        lblCosto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(255, 255, 255));
        lblCosto.setText("Costo total: $0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCosto)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTarjeta, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNuevaTarjeta, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitular)
                                    .addComponent(lblNumero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnUsarTarjeta)
                                        .addComponent(rbEfectivo))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblVencimiento)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEfectivo)
                    .addComponent(rbTarjeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsarTarjeta)
                    .addComponent(btnNuevaTarjeta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(lblVencimiento)
                    .addComponent(txtVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitular)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCVV)
                        .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
    try{

    con = conexion.conectar();

    String metodo="";

    if(rbEfectivo.isSelected()){

        metodo="Efectivo";

    }

    else if(rbTarjeta.isSelected()){

    metodo="Tarjeta";

    if(txtNumero.getText().trim().isEmpty()
    || txtTitular.getText().trim().isEmpty()
    || txtVencimiento.getText().trim().isEmpty()
    || txtCVV.getText().trim().isEmpty()){

        JOptionPane.showMessageDialog(
        null,
        "Completa los datos de la tarjeta"
        );

        return;
    }

}

    else{

        JOptionPane.showMessageDialog(
        null,
        "Selecciona un método de pago"
        );

        return;
    }

    String sql =

    "UPDATE pago p " +
    "SET metodo_pago=? " +

    "WHERE p.id_pago=(" +

    "SELECT MAX(id_pago) " +
    "FROM pago p " +

    "JOIN solicitud_viaje s " +
    "ON p.id_solicitud=s.id_solicitud " +

    "WHERE s.matricula_pasajero=?" +

    ")";

    PreparedStatement ps =
    con.prepareStatement(sql);

    ps.setString(1,metodo);

    ps.setInt(2,matriculaPasajero);

    ps.executeUpdate();
    
    String sqlEstado =
        "UPDATE pago " +
        "SET estado='Pagado' " +
        "WHERE id_pago=(" +
        "SELECT MAX(id_pago) FROM pago p " +
        "JOIN solicitud_viaje s ON p.id_solicitud=s.id_solicitud " +
        "WHERE s.matricula_pasajero=?" +
        ")";

        PreparedStatement psEstado = con.prepareStatement(sqlEstado);
        psEstado.setInt(1, matriculaPasajero);
        psEstado.executeUpdate();
        psEstado.close();
        
        String sqlViaje =
        "UPDATE solicitud_viaje " +
        "SET estado='Cerrado' " +
        "WHERE id_solicitud=(" +
        "SELECT MAX(id_solicitud) " +
        "FROM solicitud_viaje " +
        "WHERE matricula_pasajero=?" +
        ")";

        PreparedStatement psViaje = con.prepareStatement(sqlViaje);
        psViaje.setInt(1, matriculaPasajero);
        psViaje.executeUpdate();
        psViaje.close();

    if (metodo.equals("Tarjeta")) {

    if (esTarjetaNueva) {

        String sqlTarjeta =
        "INSERT INTO tarjeta(" +
        "matricula_pasajero," +
        "numero_tarjeta," +
        "titular," +
        "vencimiento" +
        ") VALUES(?,?,?,?)";

        PreparedStatement psTarjeta = con.prepareStatement(sqlTarjeta);

        psTarjeta.setInt(1, matriculaPasajero);
        psTarjeta.setString(2, txtNumero.getText());
        psTarjeta.setString(3, txtTitular.getText());
        psTarjeta.setString(4, txtVencimiento.getText());

        psTarjeta.executeUpdate();
        psTarjeta.close();
    }
}   
    
    JOptionPane.showMessageDialog(
    null,
    "Pago realizado correctamente.\nGracias por usar UniRide"
    );
    new Calificacion(matriculaPasajero).setVisible(true);
    this.dispose();

    ps.close();
    con.close();

}

catch(SQLException e){

    e.printStackTrace();

}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCVVActionPerformed

    private void rbTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTarjetaActionPerformed
    lblNumero.setVisible(true);
    txtNumero.setVisible(true);

    lblTitular.setVisible(true);
    txtTitular.setVisible(true);

    lblVencimiento.setVisible(true);
    txtVencimiento.setVisible(true);

    lblCVV.setVisible(true);
    txtCVV.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTarjetaActionPerformed

    private void rbEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEfectivoActionPerformed
    lblNumero.setVisible(false);
    txtNumero.setVisible(false);

    lblTitular.setVisible(false);
    txtTitular.setVisible(false);

    lblVencimiento.setVisible(false);
    txtVencimiento.setVisible(false);

    lblCVV.setVisible(false);
    txtCVV.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEfectivoActionPerformed

    private void btnUsarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsarTarjetaActionPerformed
    if (tieneTarjeta()) {

        rbTarjeta.setSelected(true);
        rbTarjetaActionPerformed(null);
        cargarTarjeta();
        esTarjetaNueva = false;
        JOptionPane.showMessageDialog(null,
        "Tarjeta cargada correctamente");

    } else {

        JOptionPane.showMessageDialog(null,
        "No tienes tarjeta guardada");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsarTarjetaActionPerformed

    private void btnNuevaTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTarjetaActionPerformed
    rbTarjeta.setSelected(true);
    rbTarjetaActionPerformed(null);

    txtNumero.setText("");
    txtTitular.setText("");
    txtVencimiento.setText("");
    txtCVV.setText("");
    
    esTarjetaNueva = true;

    JOptionPane.showMessageDialog(null,
    "Ingresa nueva tarjeta");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pago(0).setVisible(true)
);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaTarjeta;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnUsarTarjeta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JLabel lblVencimiento;
    private javax.swing.JRadioButton rbEfectivo;
    private javax.swing.JRadioButton rbTarjeta;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTitular;
    private javax.swing.JTextField txtVencimiento;
    // End of variables declaration//GEN-END:variables
}
