/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moral
 */
public class SolicitudesConductor extends javax.swing.JFrame {
    Connection con;

    String matriculaConductor;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SolicitudesConductor.class.getName());

    /**
     * Creates new form Solicitudes
     */
    public SolicitudesConductor() {
        initComponents();
    }
    
    public SolicitudesConductor(String matricula){

    initComponents();

    this.matriculaConductor = matricula;

    cargarSolicitudes();
}
    private void cargarSolicitudes(){

    try{

        con = conexion.conectar();

        DefaultTableModel model =
        (DefaultTableModel) tablaSolicitudes.getModel();

        model.setRowCount(0);

        String sql =
        "SELECT s.id_solicitud, " +
        "p.nombre, " +
        "s.punto_recogida, " +
        "v.origen, " +
        "v.destino " +
        "FROM solicitud_viaje s " +
        "JOIN pasajero p " +
        "ON s.matricula_pasajero=p.matricula " +
        "JOIN viaje v " +
        "ON s.id_viaje=v.id_viaje " +
        "WHERE v.matricula_conductor=?";

        PreparedStatement ps =
        con.prepareStatement(sql);

        ps.setString(1, matriculaConductor);

        ResultSet rs =
        ps.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{

            rs.getInt("id_solicitud"),
            rs.getString("nombre"),
            rs.getString("punto_recogida"),
            rs.getString("origen"),
            rs.getString("destino")

        });

        }

        rs.close();
        ps.close();
        con.close();

    }

    catch(SQLException e){

        e.printStackTrace();

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 247, 245));

        tablaSolicitudes.setForeground(new java.awt.Color(55, 65, 81));
        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Pasajero", "Punto Origen", "Origen", "Destino"
            }
        ));
        tablaSolicitudes.setGridColor(new java.awt.Color(252, 212, 194));
        tablaSolicitudes.setSelectionBackground(new java.awt.Color(232, 55, 11));
        jScrollPane1.setViewportView(tablaSolicitudes);

        btnAceptar.setBackground(new java.awt.Color(22, 163, 74));
        btnAceptar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        btnAceptar.setText("✅ Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnRechazar.setBackground(new java.awt.Color(220, 38, 38));
        btnRechazar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        btnRechazar.setText("❌ Rechazar");
        btnRechazar.setBorderPainted(false);
        btnRechazar.setFocusPainted(false);
        btnRechazar.addActionListener(this::btnRechazarActionPerformed);

        jPanel1.setBackground(new java.awt.Color(232, 55, 11));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitudes recibidas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRechazar)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
int fila=
tablaSolicitudes.getSelectedRow();

if(fila==-1){

    System.out.println(
    "Selecciona una solicitud"
    );

    return;
}

int idSolicitud=

(Integer)
tablaSolicitudes.getValueAt(
fila,
0
);

try{

    con=conexion.conectar();

    String sql=

    "UPDATE solicitud_viaje " +
    "SET estado='Aceptada' " +
    "WHERE id_solicitud=?";

    PreparedStatement ps=
    con.prepareStatement(sql);

    ps.setInt(1,idSolicitud);

    ps.executeUpdate();

    String pasajero =
tablaSolicitudes.getValueAt(fila,1).toString();

String puntoRecogida =
tablaSolicitudes.getValueAt(fila,2).toString();

JOptionPane.showMessageDialog(
null,

"Has aceptado la solicitud de: " +
pasajero +

"\n\nPunto de recogida:\n" +
puntoRecogida +

"\n\nDirígete al punto para " +
"comenzar el viaje."
);
ViajeEnCursoConductor form =
new ViajeEnCursoConductor(
matriculaConductor
);

form.setVisible(true);

this.dispose();
cargarSolicitudes();

    cargarSolicitudes();

}
catch(SQLException e){

    e.printStackTrace();

}


        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed

int fila=
tablaSolicitudes.getSelectedRow();

if(fila==-1){

    System.out.println(
    "Selecciona una solicitud"
    );

    return;
}

int idSolicitud=

(Integer)
tablaSolicitudes.getValueAt(
fila,
0
);

try{

    con=conexion.conectar();

    String sql=

    "UPDATE solicitud_viaje " +
    "SET estado='Rechazada' " +
    "WHERE id_solicitud=?";

    PreparedStatement ps=
    con.prepareStatement(sql);

    ps.setInt(
            1,
            idSolicitud
    );

    ps.executeUpdate();

    System.out.println(
    "Solicitud rechazada"
    );

    cargarSolicitudes();

}
catch(SQLException e){

    e.printStackTrace();

}


        // TODO add your handling code here:
    }//GEN-LAST:event_btnRechazarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SolicitudesConductor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
