/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author moral
 */
public class ViajeEnCursoPasajero extends javax.swing.JFrame {
     int matriculaPasajero;
     Connection con;
     boolean pagoAbierto=false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViajeEnCursoPasajero.class.getName());

    /**
     * Creates new form ViajeEnCurso
     */
    public ViajeEnCursoPasajero() {
        initComponents();
    }
    public ViajeEnCursoPasajero(int matricula){

    initComponents();

    this.matriculaPasajero =
    matricula;
    
    cargarDatosViaje();
    revisarEstadoViaje();

    javax.swing.Timer t=

    new javax.swing.Timer(
    5000,
    e -> revisarEstadoViaje()
    );

    t.start();

}
    
    private void revisarEstadoViaje(){

    try{

        con = conexion.conectar();

        String sql=

        "SELECT id_solicitud, estado " +
        "FROM solicitud_viaje " +
        "WHERE matricula_pasajero=? " +
        "ORDER BY id_solicitud DESC FETCH FIRST 1 ROWS ONLY";
        PreparedStatement ps=
        con.prepareStatement(sql);

        ps.setInt(
        1,
        matriculaPasajero
        );

        ResultSet rs=
ps.executeQuery();

if(rs.next()){

    int id = rs.getInt("id_solicitud");
    String estado = rs.getString("estado");

    System.out.println("Solicitud: " + id);
    System.out.println("Estado recibido: [" + estado + "]");

    lblEstado.setText(
    "Estado: " + estado
    );
            
            if(estado.equals("Aceptada")){

    lblMensaje.setText(
    "El conductor se dirige al punto de recogida"
    );

}

else if(estado.equals("En viaje")){

    lblMensaje.setText(
    "Tu viaje está en curso"
    );

}

else if(estado.equals("Finalizado")){

    lblMensaje.setText(
    "Has llegado a tu destino"
    );

}

            if(estado.equals("Finalizado") && !pagoAbierto){

            pagoAbierto = true;

            JOptionPane.showMessageDialog(
            null,
            "Tu viaje terminó.\n" +
            "Selecciona método de pago."
            );

            Pago form =
            new Pago(
            matriculaPasajero
            );

            form.setVisible(true);

            this.dispose();

}

        }

        rs.close();
        ps.close();
        con.close();

    }

    catch(SQLException e){

        e.printStackTrace();

    }

}
    
    private void cargarDatosViaje(){

    try{

        con = conexion.conectar();

        String sql=

        "SELECT c.nombre," +
        "s.punto_recogida," +
        "v.destino " +

        "FROM solicitud_viaje s " +

        "JOIN viaje v " +
        "ON s.id_viaje=v.id_viaje " +

        "JOIN conductor c " +
        "ON v.matricula_conductor=c.matricula " +

        "WHERE s.matricula_pasajero=? " +
        "ORDER BY s.id_solicitud DESC";

        PreparedStatement ps=
        con.prepareStatement(sql);

        ps.setInt(
        1,
        matriculaPasajero
        );

        ResultSet rs=
        ps.executeQuery();

        if(rs.next()){

            lblConductor.setText(
            "Conductor: " +
            rs.getString("nombre")
            );

            lblRecogida.setText(
            "Punto de recogida: " +
            rs.getString("punto_recogida")
            );

            lblDestino.setText(
            "Destino: " +
            rs.getString("destino")
            );

        }

        rs.close();
        ps.close();
        con.close();

    }

    catch(SQLException e){

        e.printStackTrace();

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblConductor = new javax.swing.JLabel();
        lblRecogida = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 244, 255));

        jPanel2.setBackground(new java.awt.Color(26, 86, 219));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("🚗 Viaje en curso");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 212, 240)));

        lblConductor.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblConductor.setForeground(new java.awt.Color(26, 86, 219));
        lblConductor.setText("🧑‍✈️ Conductor:");

        lblRecogida.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblRecogida.setForeground(new java.awt.Color(26, 86, 219));
        lblRecogida.setText("📍 Punto de recogida:");

        lblDestino.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(26, 86, 219));
        lblDestino.setText("🏁 Destino:");

        lblEstado.setBackground(new java.awt.Color(239, 246, 255));
        lblEstado.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(26, 86, 219));
        lblEstado.setText("🔄 Estado: esperando...");
        lblEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 212, 240)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino)
                    .addComponent(lblRecogida)
                    .addComponent(lblConductor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblConductor)
                .addGap(18, 18, 18)
                .addComponent(lblRecogida)
                .addGap(18, 18, 18)
                .addComponent(lblDestino)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 212, 240)));

        lblMensaje.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(107, 114, 128));
        lblMensaje.setText("⏳ Esperando información del conductor...");
        lblMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 212, 240)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViajeEnCursoPasajero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblConductor;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblRecogida;
    // End of variables declaration//GEN-END:variables
}
