/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author moral
 */
public class ViajeEnCursoConductor extends javax.swing.JFrame {
    //variables globales 
    Connection con;
    String matriculaConductor;
    int idSolicitud;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViajeEnCursoConductor.class.getName());

    /**
     * Creates new form ViajeEnCursoConductor
     */
   public ViajeEnCursoConductor(String matricula){

    initComponents();

    this.matriculaConductor =
    matricula;
    cargarViaje();

}
   
   private void cargarViaje(){

    try{

        con = conexion.conectar();

        String sql =
        "SELECT s.id_solicitud, " +
        "p.nombre, " +
        "s.punto_recogida, " +
        "v.destino " +

        "FROM solicitud_viaje s " +

        "JOIN pasajero p " +
        "ON s.matricula_pasajero=p.matricula " +

        "JOIN viaje v " +
        "ON s.id_viaje=v.id_viaje " +

        "WHERE v.matricula_conductor=? " +
        "AND s.estado='Aceptada'";

        PreparedStatement ps =
        con.prepareStatement(sql);

        ps.setString(1,matriculaConductor);

        ResultSet rs =
        ps.executeQuery();

        if(rs.next()){
            idSolicitud =
            rs.getInt("id_solicitud");
            
            lblPasajero.setText(
            "Pasajero: " +
            rs.getString("nombre")
            );

            lblRecogida.setText(
            "Punto: " +
            rs.getString("punto_recogida")
            );

            lblDestino.setText(
            "Destino: " +
            rs.getString("destino")
            );

            lblEstado.setText(
            "Estado: Conductor en camino"
            );

        }

        rs.close();
        ps.close();
        con.close();

    }

    catch(SQLException e){

        e.printStackTrace();

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPasajero = new javax.swing.JLabel();
        lblRecogida = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnLlegue = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 247, 245));

        jPanel2.setBackground(new java.awt.Color(232, 55, 11));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("🚗 Viaje en curso");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 212, 194)));

        lblPasajero.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        lblPasajero.setForeground(new java.awt.Color(232, 55, 11));
        lblPasajero.setText("👤 Pasajero:");

        lblRecogida.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        lblRecogida.setForeground(new java.awt.Color(232, 55, 11));
        lblRecogida.setText("📍 Punto:");

        lblDestino.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(232, 55, 11));
        lblDestino.setText("🏁 Destino:");

        lblEstado.setForeground(new java.awt.Color(232, 55, 11));
        lblEstado.setText("🔄 Estado:");

        btnLlegue.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnLlegue.setForeground(new java.awt.Color(232, 55, 11));
        btnLlegue.setText("📍 Llegué al punto ");
        btnLlegue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 55, 11)));
        btnLlegue.setFocusPainted(false);
        btnLlegue.addActionListener(this::btnLlegueActionPerformed);

        btnIniciar.setBackground(new java.awt.Color(232, 55, 11));
        btnIniciar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("🚀 Iniciar viaje");
        btnIniciar.setBorderPainted(false);
        btnIniciar.setFocusPainted(false);
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        btnFinalizar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(22, 163, 74));
        btnFinalizar.setText("✅ Finalizar viaje");
        btnFinalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 163, 74)));
        btnFinalizar.setFocusPainted(false);
        btnFinalizar.addActionListener(this::btnFinalizarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLlegue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDestino)
                            .addComponent(lblEstado))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblPasajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLlegue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
    try{

    con = conexion.conectar();

    String sql =

    "UPDATE solicitud_viaje " +
    "SET estado='En viaje' " +
    "WHERE id_solicitud=?";

    PreparedStatement ps =
    con.prepareStatement(sql);

    ps.setInt(
    1,
    idSolicitud
    );

    ps.executeUpdate();

    lblEstado.setText(
    "Estado: En viaje"
    );

    JOptionPane.showMessageDialog(
    null,
    "Viaje iniciado correctamente"
    );

    ps.close();
    con.close();

}

catch(SQLException e){

    e.printStackTrace();

}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
    try {
        System.out.println("ID solicitud que se actualizará: " + idSolicitud);
        con = conexion.conectar();
        String sql = "UPDATE solicitud_viaje SET estado='Finalizado' WHERE id_solicitud=?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, idSolicitud);
        ps.executeUpdate();
        lblEstado.setText("Estado: Finalizado");
        JOptionPane.showMessageDialog(null, "Viaje finalizado.");
        
        CalificacionConductor form =new CalificacionConductor(matriculaConductor);

        form.setVisible(true);

        this.dispose();
        ps.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
      
// TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnLlegueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlegueActionPerformed
    try{

    con = conexion.conectar();

    String sql =

    "UPDATE solicitud_viaje " +
    "SET estado='Conductor en camino' " +
    "WHERE id_solicitud=?";

    PreparedStatement ps =
    con.prepareStatement(sql);

    ps.setInt(
    1,
    idSolicitud
    );

    ps.executeUpdate();

    JOptionPane.showMessageDialog(
    null,
    "Dirígete al punto de recogida del pasajero"
    );

    lblEstado.setText(
    "Estado: Conductor en camino"
    );

    ps.close();
    con.close();

}

catch(SQLException e){

    e.printStackTrace();

}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLlegueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> 
new ViajeEnCursoConductor("0").setVisible(true)
); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLlegue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblPasajero;
    private javax.swing.JLabel lblRecogida;
    // End of variables declaration//GEN-END:variables
}
